import { SlimeDef } from './types';

// Roster ordering note: tiers step by roughly 4x rather than the old 10-15x.
// That is deliberate - it lengthens the early game and keeps a new unlock
// always within reach, instead of leaving long stretches with nothing to buy.
//
// A number of slimes take gentle inspiration from widely-known European
// folklore (household spirits, water-folk, wisps, mountain trolls). They are
// written as respectful nods to those legends rather than caricatures of any
// living culture, each names its source tradition in `originNote`, and every
// one of them is optional flavor - none is required to finish the game.
export const SLIMES: SlimeDef[] = [
  {
    id: 'basic',
    name: 'Basic Slime',
    tier: 0,
    flavor: 'Your very first slime. Wobbly, loyal, and always down to tap along.',
    baseCost: 15,
    costGrowth: 1.15,
    baseGps: 0.1,
    unlockAtLifetimeGoo: 0,
    look: { body: ['#8FE08A', '#3E9E77'], accent: '#CFF3B6', topper: 'none' },
  },
  {
    id: 'dewdrop',
    name: 'Dewdrop Slime',
    tier: 1,
    flavor: 'Condenses out of the morning air. Beads up and rolls off everything.',
    baseCost: 40,
    costGrowth: 1.15,
    baseGps: 0.32,
    unlockAtLifetimeGoo: 25,
    look: { body: ['#C8F5E4', '#6FC9C3'], accent: '#EAFBF3', topper: 'none' },
  },
  {
    id: 'puddle',
    name: 'Puddle Slime',
    tier: 2,
    flavor: 'Formed in the birdbath out back. Splashes when it produces goo.',
    baseCost: 100,
    costGrowth: 1.15,
    baseGps: 1,
    unlockAtLifetimeGoo: 60,
    look: { body: ['#8ED6F0', '#3C7FB5'], accent: '#CFEEFB', topper: 'none' },
  },
  {
    id: 'brook',
    name: 'Brook Slime',
    tier: 3,
    flavor: 'Never stops moving. Hums like running water over stones.',
    baseCost: 330,
    costGrowth: 1.15,
    baseGps: 2.8,
    unlockAtLifetimeGoo: 220,
    look: { body: ['#7FE3D6', '#2F86A8'], accent: '#BFF3EA', topper: 'fin' },
  },
  {
    id: 'mossy',
    name: 'Mossy Slime',
    tier: 4,
    flavor: 'Grows a little garden on its back. Surprisingly industrious.',
    baseCost: 1_100,
    costGrowth: 1.15,
    baseGps: 8,
    unlockAtLifetimeGoo: 800,
    look: { body: ['#A9D67C', '#4B7C3A'], accent: '#E4B7D8', topper: 'petals' },
  },
  {
    id: 'fern',
    name: 'Fernback Slime',
    tier: 5,
    flavor: 'Unfurls new fronds whenever it is complimented.',
    baseCost: 3_600,
    costGrowth: 1.15,
    baseGps: 19,
    unlockAtLifetimeGoo: 2_800,
    look: { body: ['#93D69B', '#2F7A55'], accent: '#79C88B', topper: 'coral' },
  },
  {
    id: 'ember',
    name: 'Ember Slime',
    tier: 6,
    flavor: 'Simmers instead of burns. Keeps the whole collection warm.',
    baseCost: 12_000,
    costGrowth: 1.15,
    baseGps: 47,
    unlockAtLifetimeGoo: 9_500,
    look: { body: ['#FFC46B', '#D04E28'], accent: '#FFE2A0', topper: 'flame' },
  },
  {
    id: 'cinder',
    name: 'Cinder Slime',
    tier: 7,
    flavor: 'What is left when an Ember Slime stays up too late. Still glowing.',
    baseCost: 40_000,
    costGrowth: 1.15,
    baseGps: 110,
    unlockAtLifetimeGoo: 32_000,
    look: { body: ['#E8734F', '#4A2530'], accent: '#FFB07A', topper: 'horns' },
  },
  {
    id: 'crystal',
    name: 'Crystal Slime',
    tier: 8,
    flavor: 'Formed around a geode it found and refused to let go of.',
    baseCost: 130_000,
    costGrowth: 1.15,
    baseGps: 260,
    unlockAtLifetimeGoo: 105_000,
    look: { body: ['#D3A9F0', '#6A3FA8'], accent: '#F0DDFF', topper: 'facets' },
  },
  {
    id: 'geode',
    name: 'Geode Slime',
    tier: 9,
    flavor: 'Plain on the outside. Absolutely showing off on the inside.',
    baseCost: 430_000,
    costGrowth: 1.15,
    baseGps: 600,
    unlockAtLifetimeGoo: 350_000,
    look: { body: ['#9C86D8', '#3B2A66'], accent: '#C7A6FF', topper: 'spikes' },
  },
  {
    id: 'golem',
    name: 'Golem Slime',
    tier: 10,
    flavor: 'A steady, patient protector shaped from river clay.',
    originNote:
      'Inspired by the golem of Central European Jewish folklore - a guardian animated to protect its community.',
    baseCost: 1_400_000,
    costGrowth: 1.15,
    baseGps: 1_400,
    unlockAtLifetimeGoo: 1_100_000,
    look: { body: ['#D2B183', '#7A5334'], accent: '#B08B5A', topper: 'ears' },
  },
  {
    id: 'gargoyle',
    name: 'Gargoyle Slime',
    tier: 11,
    flavor: 'Perches on the ledge all night. Comes down for goo duty at dawn.',
    originNote:
      'Inspired by the stone gargoyles of medieval European cathedrals, long described as watchful guardians.',
    baseCost: 5_300_000,
    costGrowth: 1.15,
    baseGps: 3_300,
    unlockAtLifetimeGoo: 4_200_000,
    look: { body: ['#A8B0B8', '#414B57'], accent: '#8894A2', topper: 'horns' },
  },
  {
    id: 'selkie',
    name: 'Selkie Slime',
    tier: 12,
    flavor: 'Slips out of its sealskin coat to help out on land, then slides back to sea.',
    originNote:
      'Inspired by the selkie of Scottish and Irish coastal folklore - a seal that can take human form.',
    baseCost: 20_000_000,
    costGrowth: 1.15,
    baseGps: 7_800,
    unlockAtLifetimeGoo: 16_000_000,
    look: { body: ['#8FCBDB', '#26596E'], accent: '#C6E9F2', topper: 'fin' },
  },
  {
    id: 'kelpie',
    name: 'Kelpie Slime',
    tier: 13,
    flavor: 'Offers you a ride to the far bank. Politely decline; it means well anyway.',
    originNote:
      'Inspired by the kelpie of Scottish folklore, a shape-shifting water spirit of rivers and lochs.',
    baseCost: 81_000_000,
    costGrowth: 1.15,
    baseGps: 18_500,
    unlockAtLifetimeGoo: 65_000_000,
    look: { body: ['#6FA8D6', '#1F4A5C'], accent: '#3E7F94', topper: 'ears' },
  },
  {
    id: 'wisp',
    name: 'Bog Wisp Slime',
    tier: 14,
    flavor: 'A soft, drifting light that leads the way to more goo - honest.',
    originNote: 'Inspired by will-o’-the-wisp legends found across European folklore.',
    baseCost: 330_000_000,
    costGrowth: 1.15,
    baseGps: 44_000,
    unlockAtLifetimeGoo: 260_000_000,
    look: { body: ['#EAF5A8', '#8FB84A'], accent: '#FBFFD6', topper: 'halo' },
  },
  {
    id: 'sprite',
    name: 'Sprite Slime',
    tier: 15,
    flavor: 'Too quick to catch. Rearranges your upgrades and denies everything.',
    originNote:
      'Inspired by the pixies and sprites of English and Cornish folklore, small mischievous spirits.',
    baseCost: 1_300_000_000,
    costGrowth: 1.15,
    baseGps: 107_000,
    unlockAtLifetimeGoo: 1_000_000_000,
    look: { body: ['#D9C2F5', '#5FAE9E'], accent: '#F3E6FF', topper: 'antenna' },
  },
  {
    id: 'banshee',
    name: 'Banshee Slime',
    tier: 16,
    flavor: 'Announces every big milestone with a dramatic, echoing wail of joy.',
    originNote:
      'Inspired by the banshee of Irish folklore, a spirit whose cry heralds important news.',
    baseCost: 5_100_000_000,
    costGrowth: 1.15,
    baseGps: 260_000,
    unlockAtLifetimeGoo: 4_100_000_000,
    look: { body: ['#E2E2F7', '#7B7BB4'], accent: '#FFFFFF', topper: 'halo' },
  },
  {
    id: 'brownie',
    name: 'Brownie Slime',
    tier: 17,
    flavor: 'Tidies the whole collection overnight. Leave it a bowl of cream.',
    originNote:
      'Inspired by the brownie of Scottish and English folklore, a household spirit that helps in exchange for small gifts.',
    baseCost: 20_000_000_000,
    costGrowth: 1.15,
    baseGps: 645_000,
    unlockAtLifetimeGoo: 16_000_000_000,
    look: { body: ['#D8A96B', '#6B3F2A'], accent: '#F0D2A0', topper: 'ears' },
  },
  {
    id: 'troll',
    name: 'Troll Slime',
    tier: 18,
    flavor: 'Guards the bridge to the next tier. Charges a very reasonable toll.',
    originNote:
      'Inspired by the trolls of Scandinavian folklore, mountain- and bridge-dwelling guardians.',
    baseCost: 75_000_000_000,
    costGrowth: 1.15,
    baseGps: 1_600_000,
    unlockAtLifetimeGoo: 60_000_000_000,
    look: { body: ['#A3B583', '#3E4E36'], accent: '#D7C48F', topper: 'horns' },
  },
  {
    id: 'gnome',
    name: 'Gnome Slime',
    tier: 19,
    flavor: 'Knows exactly where everything is buried. Will not be telling you.',
    originNote:
      'Inspired by the gnome of European folklore, an earth-dwelling keeper of underground things.',
    baseCost: 270_000_000_000,
    costGrowth: 1.15,
    baseGps: 4_000_000,
    unlockAtLifetimeGoo: 215_000_000_000,
    look: { body: ['#E0785F', '#5C3A2E'], accent: '#FFD9A8', topper: 'crown' },
  },
  {
    id: 'cosmic',
    name: 'Cosmic Slime',
    tier: 20,
    flavor: 'Not from folklore, not from Earth. Just really, really good at making goo.',
    baseCost: 1_000_000_000_000,
    costGrowth: 1.15,
    baseGps: 10_000_000,
    unlockAtLifetimeGoo: 800_000_000_000,
    look: { body: ['#A88FF0', '#3A2585'], accent: '#E4D6FF', topper: 'crown' },
  },
  {
    id: 'astral',
    name: 'Astral Slime',
    tier: 21,
    flavor: 'Arrived from somewhere further out than the Cosmic Slime. They do not discuss it.',
    baseCost: 12_000_000_000_000,
    costGrowth: 1.15,
    baseGps: 65_000_000,
    unlockAtLifetimeGoo: 9_500_000_000_000,
    look: { body: ['#7FE9F0', '#4B2E9E'], accent: '#D8FBFF', topper: 'facets' },
  },
];

export const SLIME_BY_ID: Record<string, SlimeDef> = Object.fromEntries(
  SLIMES.map((s) => [s.id, s])
);
