import { SlimeDef } from './types';

// A handful of the later slimes draw on widely-known European folklore
// spirits (household guardians, sea-folk, will-o'-the-wisps, mountain
// trolls). They're written as gentle, respectful nods to the source
// legends rather than caricatures of any living culture, and every one of
// them is purely optional flavor - none is required to finish the game.
export const SLIMES: SlimeDef[] = [
  {
    id: 'basic',
    name: 'Basic Slime',
    tier: 0,
    flavor: 'Your very first slime. Wobbly, loyal, and always down to tap along.',
    baseCost: 15,
    costGrowth: 1.15,
    baseGps: 0.1,
    unlockAtLifetimeGoo: 0,
    emoji: '🟢',
    colors: ['#7CE07C', '#3FA34D'],
  },
  {
    id: 'puddle',
    name: 'Puddle Slime',
    tier: 1,
    flavor: 'Formed in the birdbath out back. Splashes when it produces goo.',
    baseCost: 100,
    costGrowth: 1.15,
    baseGps: 1,
    unlockAtLifetimeGoo: 50,
    emoji: '💧',
    colors: ['#7EC8E3', '#2E86AB'],
  },
  {
    id: 'mossy',
    name: 'Mossy Slime',
    tier: 2,
    flavor: 'Grows a little garden on its back. Surprisingly industrious.',
    baseCost: 1_100,
    costGrowth: 1.15,
    baseGps: 8,
    unlockAtLifetimeGoo: 1_000,
    emoji: '🌿',
    colors: ['#9BC46B', '#4E7A34'],
  },
  {
    id: 'ember',
    name: 'Ember Slime',
    tier: 3,
    flavor: 'Simmers instead of burns. Keeps the whole collection warm.',
    baseCost: 12_000,
    costGrowth: 1.15,
    baseGps: 47,
    unlockAtLifetimeGoo: 12_000,
    emoji: '🔥',
    colors: ['#FFA24C', '#D9531E'],
  },
  {
    id: 'crystal',
    name: 'Crystal Slime',
    tier: 4,
    flavor: "Formed around a geode it found and refused to let go of.",
    baseCost: 130_000,
    costGrowth: 1.15,
    baseGps: 260,
    unlockAtLifetimeGoo: 130_000,
    emoji: '💎',
    colors: ['#B695E0', '#6C3FA0'],
  },
  {
    id: 'golem',
    name: 'Golem Slime',
    tier: 5,
    flavor: 'A steady, patient protector shaped from river clay.',
    originNote: 'Inspired by the golem of Central European Jewish folklore - a guardian animated to protect its community.',
    baseCost: 1_400_000,
    costGrowth: 1.15,
    baseGps: 1_400,
    unlockAtLifetimeGoo: 1_400_000,
    emoji: '🗿',
    colors: ['#B08B5A', '#7A5C34'],
  },
  {
    id: 'selkie',
    name: 'Selkie Slime',
    tier: 6,
    flavor: 'Slips out of its sealskin coat to help out on land, then slides back to sea.',
    originNote: 'Inspired by the selkie of Scottish and Irish coastal folklore - a seal that can take human form.',
    baseCost: 20_000_000,
    costGrowth: 1.15,
    baseGps: 7_800,
    unlockAtLifetimeGoo: 20_000_000,
    emoji: '🦭',
    colors: ['#6FB6C7', '#2C6E7F'],
  },
  {
    id: 'wisp',
    name: 'Bog Wisp Slime',
    tier: 7,
    flavor: 'A soft, drifting light that leads the way to more goo - honest.',
    originNote: 'Inspired by will-o’-the-wisp legends found across European folklore.',
    baseCost: 330_000_000,
    costGrowth: 1.15,
    baseGps: 44_000,
    unlockAtLifetimeGoo: 330_000_000,
    emoji: '🌟',
    colors: ['#DDEB8F', '#9CBF3E'],
  },
  {
    id: 'banshee',
    name: 'Banshee Slime',
    tier: 8,
    flavor: 'Announces every big milestone with a dramatic, echoing wail of joy.',
    originNote: 'Inspired by the banshee of Irish folklore, a spirit whose cry heralds important news.',
    baseCost: 5_100_000_000,
    costGrowth: 1.15,
    baseGps: 260_000,
    unlockAtLifetimeGoo: 5_100_000_000,
    emoji: '👻',
    colors: ['#C9C9E8', '#7676B0'],
  },
  {
    id: 'troll',
    name: 'Troll Slime',
    tier: 9,
    flavor: 'Guards the bridge to the next tier. Charges a very reasonable toll.',
    originNote: 'Inspired by the trolls of Scandinavian folklore, mountain- and bridge-dwelling guardians.',
    baseCost: 75_000_000_000,
    costGrowth: 1.15,
    baseGps: 1_600_000,
    unlockAtLifetimeGoo: 75_000_000_000,
    emoji: '🧌',
    colors: ['#8FA377', '#4E5E3E'],
  },
  {
    id: 'cosmic',
    name: 'Cosmic Slime',
    tier: 10,
    flavor: 'Not from folklore, not from Earth. Just really, really good at making goo.',
    baseCost: 1_000_000_000_000,
    costGrowth: 1.15,
    baseGps: 10_000_000,
    unlockAtLifetimeGoo: 1_000_000_000_000,
    emoji: '✨',
    colors: ['#8E7CE0', '#3E2C8F'],
  },
];

export const SLIME_BY_ID: Record<string, SlimeDef> = Object.fromEntries(
  SLIMES.map((s) => [s.id, s])
);
