import { TapUpgradeDef } from './types';

// Every upgrade below is bought with in-game goo. There is nothing in this
// list, or anywhere in the free upgrade tree, that requires real money -
// paid add-ons (see addOnData.ts) only ever offer small, optional extras.
export const TAP_UPGRADES: TapUpgradeDef[] = [
  {
    id: 'tap_1',
    name: 'Sticky Fingers',
    description: '+1 goo per tap.',
    cost: 50,
    addPower: 1,
    unlockAtLifetimeGoo: 0,
    emoji: '👆',
  },
  {
    id: 'tap_2',
    name: 'Two-Finger Tap',
    description: '+2 goo per tap.',
    cost: 500,
    addPower: 2,
    unlockAtLifetimeGoo: 300,
    emoji: '✌️',
  },
  {
    id: 'tap_3',
    name: 'Slime Gloves',
    description: '+4 goo per tap.',
    cost: 5_000,
    addPower: 4,
    unlockAtLifetimeGoo: 3_000,
    emoji: '🧤',
  },
  {
    id: 'tap_4',
    name: 'Bouncy Palm',
    description: '+9 goo per tap.',
    cost: 60_000,
    addPower: 9,
    unlockAtLifetimeGoo: 35_000,
    emoji: '🫳',
  },
  {
    id: 'tap_5',
    name: 'Double Tap Technique',
    description: '+20 goo per tap.',
    cost: 700_000,
    addPower: 20,
    unlockAtLifetimeGoo: 400_000,
    emoji: '👏',
  },
  {
    id: 'tap_6',
    name: 'Reinforced Screen Protector',
    description: '+45 goo per tap.',
    cost: 8_000_000,
    addPower: 45,
    unlockAtLifetimeGoo: 5_000_000,
    emoji: '📱',
  },
  {
    id: 'tap_7',
    name: 'Golem-Grip Gauntlet',
    description: '+100 goo per tap.',
    cost: 90_000_000,
    addPower: 100,
    unlockAtLifetimeGoo: 60_000_000,
    emoji: '🥊',
  },
  {
    id: 'tap_8',
    name: 'Selkie-Blessed Fingertips',
    description: '+250 goo per tap.',
    cost: 1_100_000_000,
    addPower: 250,
    unlockAtLifetimeGoo: 700_000_000,
    emoji: '🫰',
  },
  {
    id: 'tap_9',
    name: 'Wisp-Light Reflexes',
    description: '+600 goo per tap.',
    cost: 14_000_000_000,
    addPower: 600,
    unlockAtLifetimeGoo: 9_000_000_000,
    emoji: '⚡',
  },
  {
    id: 'tap_10',
    name: 'Cosmic Tap',
    description: '+1,500 goo per tap.',
    cost: 2_000_000_000_000,
    addPower: 1_500,
    unlockAtLifetimeGoo: 1_200_000_000_000,
    emoji: '🌌',
  },
];
